<?php 

$rutTrabajador = $_SESSION['rutTrabajador'];
$dvTrabajador = $_SESSION['dvTrabajador'];

$sql = "SELECT 
EVALUACION.ID_EVALUACION, 
EVALUACION.CARGO,
TRABAJADOR.ID_TRABAJADOR, 
RUT_TRABAJADOR, 
DV_TRABAJADOR, 
NOMBRE_TRABAJADOR, 
APELLIDO_TRABAJADOR, 
NOMBRE_USUARIO, 
APELLIDO_USUARIO, 
FECHA_CREACION, 
EVALUACION.ID_USUARIO, 
HORA_CREACION 
FROM EVALUACION 
INNER JOIN TRABAJADOR 
ON EVALUACION.ID_TRABAJADOR = TRABAJADOR.ID_TRABAJADOR 
INNER JOIN USUARIO 
ON EVALUACION.ID_USUARIO = USUARIO.ID_USUARIO 
WHERE TRABAJADOR.RUT_TRABAJADOR = '$rutTrabajador' AND TRABAJADOR.DV_TRABAJADOR = '$dvTrabajador' AND EVALUACION.PENDIENTE_REVISION_MEDICA = 2
ORDER BY EVALUACION.FECHA_CREACION DESC, EVALUACION.HORA_CREACION DESC"; 

//echo $sql;
?>
